-- CELA tier assignment — sets crm_firms.tier (1-4) by attorney name.
-- Run ONCE in the Supabase SQL editor AFTER cela_firms_seed.sql. Idempotent.
-- 4 call-angle/objection templates live in code (TIER_PLAYS), not per-row.

alter table public.crm_firms add column if not exists tier smallint;

with t (attorney_name, tier) as (
  values
  ('Andrew L. Thrasher', 1),
  ('Catharine McGlynn', 1),
  ('Lawrance Bohm', 1),
  ('Zane Hilton', 1),
  ('John Vincent Ricca', 1),
  ('Emil Davtyan', 1),
  ('Emilia Mehrabian', 1),
  ('Jean Hopkins Power', 1),
  ('Kelsey Ciarimboli', 1),
  ('Renia Zadourian', 1),
  ('Kyle Weinheimer', 2),
  ('Mark Stephen Adams', 2),
  ('Parnell Fox', 2),
  ('Alexander McKay', 2),
  ('Brittany Victoria Berzin', 2),
  ('Connor Olson', 2),
  ('David Graulich', 2),
  ('James Clark', 2),
  ('James H Baker Jr.', 2),
  ('Julian Burns King', 2),
  ('Renee Parras Ortega', 2),
  ('Adam Koshkin', 2),
  ('Ally N. Girouard', 2),
  ('Arlo Uriarte', 2),
  ('Ashleigh Alexa Musser', 2),
  ('Ashley N. Pellouchoud', 2),
  ('Bradan Litzinger', 2),
  ('Candice Clipner', 2),
  ('Carole L Okolwicz', 2),
  ('Caroline Louise Hill', 2),
  ('Carolyn H. Cottrell', 2),
  ('Christian Schreiber', 2),
  ('Christopher LeClerc', 2),
  ('Cody Alexander Bolce', 2),
  ('Conor Trombetta', 2),
  ('Daniel Brome', 2),
  ('David A. Lowe', 2),
  ('David S. Ratner', 2),
  ('Eileen Goldsmith', 2),
  ('Elana Jacobs', 2),
  ('Elizabeth R Klos', 2),
  ('Emile Davis', 2),
  ('Erin Pulaski', 2),
  ('Estefania Palacios', 2),
  ('Eve Cervantez', 2),
  ('Gay Crosthwait Grunfeld', 2),
  ('Gelian Belong', 2),
  ('George A Warner', 2),
  ('Hector Martinez', 2),
  ('James Michael Finberg', 2),
  ('Jane B. Mackie', 2),
  ('Jenny Yelin', 2),
  ('Jeremy V. Reyes', 2),
  ('Jessica Juarez', 2),
  ('Jessica Peri Spierer', 2),
  ('Joe Bautista', 2),
  ('John T Mullan', 2),
  ('Katie Fiester', 2),
  ('Latika Moti Malkani', 2),
  ('Laura Herron Weber', 2),
  ('Maria Bourn', 2),
  ('Marjorie Wallace', 2),
  ('Mark LeClerc', 2),
  ('Matthew Helland', 2),
  ('Matthew J Flynn', 2),
  ('Menaka Fernando', 2),
  ('Michelle G. Lee', 2),
  ('Molly Frandsen', 2),
  ('Monique Olivier', 2),
  ('Peter F. Lacques', 2),
  ('Rahel H Alazar', 2),
  ('Ramsey Hanafi', 2),
  ('Rebecca Peterson-Fisher', 2),
  ('Rebecca Wildman-Tobriner', 2),
  ('Robert Michael Flynn', 2),
  ('Shannon Seibert', 2),
  ('Shelley Molineaux', 2),
  ('Stephen A Sommers', 2),
  ('Steven Tindall', 2),
  ('Valerie Leones-Ramos', 2),
  ('Vanessa C. Deniston', 2),
  ('Zoe DeGeer', 2),
  ('Angelique Mangaser', 2),
  ('Brian Angelini', 2),
  ('Calyn Vernay Hadlock', 2),
  ('Carney Shegerian', 2),
  ('Danielle Langella', 2),
  ('Danielle Sweets Worthy', 2),
  ('Erum Siddiqui', 2),
  ('Nissim Levin', 2),
  ('Ryan Chuman', 2),
  ('Ryan Quadrel', 2),
  ('Todd Harrison', 2),
  ('Toni Lambert', 2),
  ('Carla Minnard', 3),
  ('Charlene Tsai', 3),
  ('Daniel Richardson', 3),
  ('Daniel Todd Newman', 3),
  ('Donald R. Williams Jr.', 3),
  ('Douglas M. Egbert', 3),
  ('Drew Lewis', 3),
  ('George Allen', 3),
  ('Jill Patricia Telfer', 3),
  ('John Robert Parker Jr.', 3),
  ('Kelsey A. Webber', 3),
  ('Melissa Yoest', 3),
  ('Michael S. Ahmad', 3),
  ('Noah Schwinghamer', 3),
  ('Robert Boucher', 3),
  ('Rudolph Delson', 3),
  ('Scot D. Bernstein', 3),
  ('Aaron Kaufmann', 3),
  ('Alan Cohen', 3),
  ('Alison Kosinski', 3),
  ('Amy Endo', 3),
  ('Amy Morgenstern', 3),
  ('Andrea Alejandra Nunez', 3),
  ('Andrea Loh', 3),
  ('Andy Katz', 3),
  ('Anthony Sperber', 3),
  ('Benjamin K. Karpilow', 3),
  ('Beth Wolf Mora', 3),
  ('Bobby Shukla', 3),
  ('Brent A. Robinson', 3),
  ('Bruce J. Highman', 3),
  ('Bruce Weisenberg', 3),
  ('Bryan McCormack', 3),
  ('Bryan Schwartz', 3),
  ('Catha Worthman', 3),
  ('Claire Elizabeth Cochran', 3),
  ('Cliff Palefsky', 3),
  ('Cristina Molteni', 3),
  ('Curtis Allen', 3),
  ('Danielle A Fuschetti', 3),
  ('Darci Elaine Burrell', 3),
  ('David T. Wang', 3),
  ('Deborah England', 3),
  ('Deborah Kochan', 3),
  ('Devin Coyle', 3),
  ('Dow Wakefield Patten', 3),
  ('Dustin L. Collier', 3),
  ('Elizabeth Gropman', 3),
  ('Elizabeth Rose Malay', 3),
  ('Emily McGrath', 3),
  ('Emily Nugent', 3),
  ('Genevieve K. Guertin', 3),
  ('Genevieve L. Casey', 3),
  ('George R. Nemiroff', 3),
  ('Glicel Sumagaysay', 3),
  ('Gordon Kaupp', 3),
  ('Grainne Callan', 3),
  ('Gregory G Paul', 3),
  ('Hannah Kieschnick', 3),
  ('Hillary Benham-Baker', 3),
  ('Jason Erlich', 3),
  ('Jayme L. Walker', 3),
  ('Jeannette A. Vaccaro', 3),
  ('Jennifer A. Reisch', 3),
  ('Jeremy Pasternak', 3),
  ('Joseph D. Sutton', 3),
  ('Joshua Konecky', 3),
  ('Julianne Stanford', 3),
  ('Justin Clark', 3),
  ('Kathryn Bain', 3),
  ('Kelly Armstrong', 3),
  ('Ken Boyd', 3),
  ('Kira Brekke', 3),
  ('Laura Mazza', 3),
  ('Leonard Emma', 3),
  ('Maraka Willits', 3),
  ('Mark Potter', 3),
  ('Mark Scott Thuesen', 3),
  ('Mathew N Stephenson', 3),
  ('Matthew Peter Vandall', 3),
  ('Matthew Righetti', 3),
  ('Melody Rissell Leonard', 3),
  ('Michelle L. Roberts', 3),
  ('Michelle Neumann', 3),
  ('Moira McQuaid', 3),
  ('Monali Sheth', 3),
  ('Navruz Avloni', 3),
  ('Paul Glusman', 3),
  ('Paul Pfeilschiefter', 3),
  ('Phil Horowitz', 3),
  ('Rachel Terp', 3),
  ('Rebecca Kagin', 3),
  ('Reed W. L. Marcy', 3),
  ('Rene Potter', 3),
  ('Richard Vaznaugh', 3),
  ('Robert Spencer', 3),
  ('Robert Stewart Jaret', 3),
  ('Ryan Hicks', 3),
  ('Sarah Nichols', 3),
  ('Scott M. Stillman', 3),
  ('Sean McHenry', 3),
  ('Sharon Vinick', 3),
  ('Sinclaire Parer', 3),
  ('Stacy Y. North', 3),
  ('Stephen Henry', 3),
  ('Stephen R. Jaffe', 3),
  ('Supreeta Sampath', 3),
  ('Taylor Bell Graham', 3),
  ('Terry R. Leoni', 3),
  ('Tom Skinner', 3),
  ('Traci Michelle Hinden', 3),
  ('Trey Sims', 3),
  ('Vincent Tong', 3),
  ('Virginia Villegas', 3),
  ('Waukeen Q McCoy', 3),
  ('Wendy Musell', 3),
  ('Xiaoqing Zhang', 3),
  ('Xinying Valerian', 3),
  ('Yosef Peretz', 3),
  ('Adam Reisner', 3),
  ('Alex P. Katofsky', 3),
  ('Alicia Olivares', 3),
  ('Alvin Ferrara', 3),
  ('Alyze Rosabelle Salan', 3),
  ('Angie M. Kwik', 3),
  ('Annie Ksadzhikyan', 3),
  ('April Macaraeg', 3),
  ('Aram Rostomyan', 3),
  ('Arrash Tayefeh Fattahi', 3),
  ('Ashkan Shakouri', 3),
  ('Beth Anne Gunn', 3),
  ('Bita Neyestani', 3),
  ('Bradley J. Mancuso', 3),
  ('Brandon S Younesi', 3),
  ('Brian Y. Shirazi', 3),
  ('Brooke Reno', 3),
  ('Bryan J Lazarski', 3),
  ('C. Joe Sayas Jr.', 3),
  ('Carly Nese', 3),
  ('Catherine Roland', 3),
  ('Charles Rho', 3),
  ('Charles S. Feigelstock', 3),
  ('Christian Daniel Girgis', 3),
  ('Christina Humphrey', 3),
  ('Christopher Berberian', 3),
  ('Cornelia Dai', 3),
  ('Daniel Isack Cohen', 3),
  ('Daniel Nomanim', 3),
  ('Daniel Reisman', 3),
  ('David M. Saldana', 3),
  ('David Safvati', 3),
  ('Diana Gevorkian', 3),
  ('Douglas N. Silverstein', 3),
  ('Elena Medina Torres', 3),
  ('Eliot J Rushovich', 3),
  ('Emanuel Starr', 3),
  ('Emily Rose Pincin', 3),
  ('Eugenia Hicks', 3),
  ('Fred G Quiel', 3),
  ('Greg Taylor', 3),
  ('Harley M Phleger', 3),
  ('Heather K. McMillan', 3),
  ('Jacob Nalbandyan', 3),
  ('Janeth Arias', 3),
  ('Jared Richard Sohn', 3),
  ('Jeffrey Rager', 3),
  ('Jeffrey W. Cowan', 3),
  ('Jennifer Milazzo', 3),
  ('Jillian Fairchild', 3),
  ('Jonathan Weinman', 3),
  ('Joseph Richards', 3),
  ('Joshua Klugman', 3),
  ('Karina Godoy', 3),
  ('Karl Gerber', 3),
  ('Kaveh S. Elihu', 3),
  ('Kaylina Castellanos', 3),
  ('Kelly Hanker', 3),
  ('Kyle Pruner', 3),
  ('Lauren Abrams', 3),
  ('Louis JAY Cohen', 3),
  ('Mark H. Wagner', 3),
  ('Martin Isaac Aarons', 3),
  ('Matthew A. Kaufman', 3),
  ('Matthew Gutierrez', 3),
  ('Michael Chakrian', 3),
  ('Michael Kol Blue', 3),
  ('Monique R. Rodriguez', 3),
  ('Morgan Good', 3),
  ('Nathalie Meza Contreras', 3),
  ('Nicole Meyers', 3),
  ('Nicole Ricotta', 3),
  ('Nikka Maleki', 3),
  ('Nima Javaherian', 3),
  ('Nima Shivayi', 3),
  ('Payam Aframian', 3),
  ('Philip Horlacher', 3),
  ('Robert Zavala', 3),
  ('Romina Keshishyan', 3),
  ('Sam Setyan', 3),
  ('Samuel Nielson', 3),
  ('Shahla Judith Moussly', 3),
  ('Stephanie P. Kasis', 3),
  ('Steven Witt', 3),
  ('Susan Swan', 3),
  ('Suzanne Patricia Porrazzo', 3),
  ('Tara Hattendorf', 3),
  ('Ted Holmquist', 3),
  ('Tessa King', 3),
  ('Tina Mehr', 3),
  ('Toni Jaramilla', 3),
  ('Tyler Clark', 3),
  ('Victoria V. Felder', 3),
  ('Vincent Calderone', 3),
  ('Whitney Betts', 3),
  ('Wilmer J. Harris', 3),
  ('Zachariah E Moura', 3),
  ('Zareh Jaltorossian', 3),
  ('Valerie O''Dell', 4),
  ('Anastasia Bronski', 4),
  ('Art Siegel', 4),
  ('Byron Goldstein', 4),
  ('Emily Thomas', 4),
  ('Enrique Martinez', 4),
  ('Evan Ettinghoff', 4),
  ('Jacqueline R Crispino', 4),
  ('Kurt Walter Dreger', 4),
  ('Meghan F. Loisel', 4),
  ('Michael Brooks', 4),
  ('Rachel Hallam', 4),
  ('Sonya Z Mehta', 4),
  ('Steven Elster', 4),
  ('Tamarah P. Prevost', 4),
  ('Alexander Vialy', 4),
  ('Allison Norder', 4),
  ('Angelica J. Caro', 4),
  ('Babak Nehoray', 4),
  ('Brooke Bellah', 4),
  ('Cameron Holl', 4),
  ('Elena Victoria Mekikyan', 4),
  ('Emily Hanh Bui Filkin', 4),
  ('James Park', 4),
  ('Jessica Gomez', 4),
  ('Jinni Kang', 4),
  ('Jordanna Gabrielle Thigpen', 4),
  ('Jorge Humberto Reyes', 4),
  ('Joshua Cohen Slatkin', 4),
  ('Laura Christine Fentonmiller', 4),
  ('Lauren Davis', 4),
  ('Lawrence James Lennemann', 4),
  ('London Dominic Webster', 4),
  ('Nilay Vora', 4),
  ('Pedram Javanmardi', 4),
  ('Raphael Hedwat', 4),
  ('Sanaz Imani', 4),
  ('Susan Rebecca Huerta', 4),
  ('Young Park', 4)
)
update public.crm_firms c
set tier = t.tier
from t
where c.attorney_name = t.attorney_name;
